### PR TITLE
Added parameters link to sqlRecipients

### LINKED ISSUE #142: Add parameters button to SQL Recipients Similar to Notification Config
## Is your feature request related to a problem? Please describe

It's not obvious how to open the parameter editor on the Recipient SQL Query View...
Image
https://github.com/openmsupply/notify/pull/123#issuecomment-1728613855

## Describe the solution you'd like

image

### PR DESCRIPTION
**Pull request by jmbrunskill**
Closes #142 

# 👩🏻‍💻 What does this PR do?
 
Adds a parameters button to top of sql recipients screen

# 🧪 How has/should this change been tested?

Check that the parameters button shows at the top right hand side of the SQL recipients page.
Test that parameters panel can be re-opened if closed by the user.

### CODE REVIEW

**Comment by Mai21** [comment]
When we click on 'New Query', Modal title is 'Setup Notification'. It will be 'Create Query' or something?
Screenshot 2023-09-25 at 5 17 29 PM

**Comment by jmbrunskill** [comment]
> When we click on 'New Query', Modal title is 'Setup Notification'. It will be 'Create Query' or something? Screenshot 2023-09-25 at 5 17 29 PM

Fixed in https://github.com/openmsupply/notify/pull/146/commits/cd42f1d12d8e8515061c2daa7b9625d26c0cacd5

**Review by Mai21 — APPROVED** [review]
Looks good to me!

**Comment by Mai21** [comment]
@jmbrunskill Sorry, in terms of 'New Query' above, this is the wrong PR to comment on!

**Pull request merged**
